//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot_Motivator.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bot_Motivator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0457948e46b87c4 {
            get {
                object obj = ResourceManager.GetObject("0457948e46b87c4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0457948e46b87c41 {
            get {
                object obj = ResourceManager.GetObject("0457948e46b87c41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1128_30 {
            get {
                object obj = ResourceManager.GetObject("_1128-30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _123 {
            get {
                object obj = ResourceManager.GetObject("123", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1234 {
            get {
                object obj = ResourceManager.GetObject("1234", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12341 {
            get {
                object obj = ResourceManager.GetObject("12341", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12342 {
            get {
                object obj = ResourceManager.GetObject("12342", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12343 {
            get {
                object obj = ResourceManager.GetObject("12343", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12344 {
            get {
                object obj = ResourceManager.GetObject("12344", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _260322 {
            get {
                object obj = ResourceManager.GetObject("260322", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4167273_business_wallpaper {
            get {
                object obj = ResourceManager.GetObject("4167273-business-wallpaper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _576552d6e73f015563cb97a3 {
            get {
                object obj = ResourceManager.GetObject("576552d6e73f015563cb97a3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7e1bdc48673b98d927607ff0b5739042 {
            get {
                object obj = ResourceManager.GetObject("7e1bdc48673b98d927607ff0b5739042", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8cEjz8zKi {
            get {
                object obj = ResourceManager.GetObject("8cEjz8zKi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8cEjz8zKi1 {
            get {
                object obj = ResourceManager.GetObject("8cEjz8zKi1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8cEjz8zKi2 {
            get {
                object obj = ResourceManager.GetObject("8cEjz8zKi2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8cEjz8zKi3 {
            get {
                object obj = ResourceManager.GetObject("8cEjz8zKi3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _94895011_abstract_technology_background_hi_tech_communication_concept_innovation_background_vector_illustrati {
            get {
                object obj = ResourceManager.GetObject("94895011-abstract-technology-background-hi-tech-communication-concept-innovation-" +
                        "background-vector-illustrati", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _94895011_abstract_technology_background_hi_tech_communication_concept_innovation_background_vector_illustrati1 {
            get {
                object obj = ResourceManager.GetObject("94895011-abstract-technology-background-hi-tech-communication-concept-innovation-" +
                        "background-vector-illustrati1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_cyan_blue_stripes_motion_background_video_animation_ultra_hd_4k_3840x2160_scyvvwote_thumbnail_full06 {
            get {
                object obj = ResourceManager.GetObject("abstract-cyan-blue-stripes-motion-background-video-animation-ultra-hd-4k-3840x216" +
                        "0_scyvvwote_thumbnail-full06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_cyan_blue_stripes_motion_background_video_animation_ultra_hd_4k_3840x2160_scyvvwote_thumbnail_full061 {
            get {
                object obj = ResourceManager.GetObject("abstract-cyan-blue-stripes-motion-background-video-animation-ultra-hd-4k-3840x216" +
                        "0_scyvvwote_thumbnail-full061", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_cyan_blue_stripes_motion_background_video_animation_ultra_hd_4k_3840x2160_scyvvwote_thumbnail_full062 {
            get {
                object obj = ResourceManager.GetObject("abstract-cyan-blue-stripes-motion-background-video-animation-ultra-hd-4k-3840x216" +
                        "0_scyvvwote_thumbnail-full062", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_cyan_blue_stripes_motion_background_video_animation_ultra_hd_4k_3840x2160_scyvvwote_thumbnail_full063 {
            get {
                object obj = ResourceManager.GetObject("abstract-cyan-blue-stripes-motion-background-video-animation-ultra-hd-4k-3840x216" +
                        "0_scyvvwote_thumbnail-full063", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_cyan_blue_stripes_motion_background_video_animation_ultra_hd_4k_3840x2160_scyvvwote_thumbnail_full064 {
            get {
                object obj = ResourceManager.GetObject("abstract-cyan-blue-stripes-motion-background-video-animation-ultra-hd-4k-3840x216" +
                        "0_scyvvwote_thumbnail-full064", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_cyan_blue_stripes_motion_background_video_animation_ultra_hd_4k_3840x2160_scyvvwote_thumbnail_full065 {
            get {
                object obj = ResourceManager.GetObject("abstract-cyan-blue-stripes-motion-background-video-animation-ultra-hd-4k-3840x216" +
                        "0_scyvvwote_thumbnail-full065", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstrait_bleu_formes_geometriques_1017_15490 {
            get {
                object obj = ResourceManager.GetObject("abstrait-bleu-formes-geometriques_1017-15490", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstrait_bleu_formes_geometriques_1017_154901 {
            get {
                object obj = ResourceManager.GetObject("abstrait-bleu-formes-geometriques_1017-154901", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ada6cfb3a16edc1ee1107008dfbd79cd {
            get {
                object obj = ResourceManager.GetObject("ada6cfb3a16edc1ee1107008dfbd79cd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ada6cfb3a16edc1ee1107008dfbd79cd1 {
            get {
                object obj = ResourceManager.GetObject("ada6cfb3a16edc1ee1107008dfbd79cd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_and_white_abstract_background_8 {
            get {
                object obj = ResourceManager.GetObject("blue-and-white-abstract-background-8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_background_abstract_wallpapers_55298_2044051 {
            get {
                object obj = ResourceManager.GetObject("blue-background-abstract-wallpapers-55298-2044051", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_waves_wallpapers_55341_752016 {
            get {
                object obj = ResourceManager.GetObject("blue-waves-wallpapers-55341-752016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_fashion_background_vector_material_dynamic_lines {
            get {
                object obj = ResourceManager.GetObject("download-fashion-background-vector-material-dynamic-lines", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_fashion_background_vector_material_dynamic_lines1 {
            get {
                object obj = ResourceManager.GetObject("download-fashion-background-vector-material-dynamic-lines1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kavaynye_kotiki_kartinki_dlya_srisovki_8 {
            get {
                object obj = ResourceManager.GetObject("kavaynye-kotiki-kartinki-dlya-srisovki-8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kcMKLrg6i {
            get {
                object obj = ResourceManager.GetObject("kcMKLrg6i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Light_blue_wavy_abstract_background_vector_02 {
            get {
                object obj = ResourceManager.GetObject("Light-blue-wavy-abstract-background-vector-02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Light_blue_wavy_abstract_background_vector_021 {
            get {
                object obj = ResourceManager.GetObject("Light-blue-wavy-abstract-background-vector-021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Negative {
            get {
                object obj = ResourceManager.GetObject("Negative", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NegativeNOBACK {
            get {
                object obj = ResourceManager.GetObject("NegativeNOBACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NegativeNOBACK1 {
            get {
                object obj = ResourceManager.GetObject("NegativeNOBACK1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NegativeNOBACK2 {
            get {
                object obj = ResourceManager.GetObject("NegativeNOBACK2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap orig {
            get {
                object obj = ResourceManager.GetObject("orig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Positive {
            get {
                object obj = ResourceManager.GetObject("Positive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PoSPositive {
            get {
                object obj = ResourceManager.GetObject("PoSPositive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psd_light_blue_flat_dotted_line_background_heypik_8XU43VE {
            get {
                object obj = ResourceManager.GetObject("psd-light-blue-flat-dotted-line-background-heypik-8XU43VE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rovno {
            get {
                object obj = ResourceManager.GetObject("rovno", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap timetable {
            get {
                object obj = ResourceManager.GetObject("timetable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap videoblocks_blue_abstract_corporate_grunge_waves_motion_background_video_animation_ultra_hd_4k_3840x2160_srjoecgyz_thumbnail_full01_on_blue_abstract {
            get {
                object obj = ResourceManager.GetObject("videoblocks-blue-abstract-corporate-grunge-waves-motion-background-video-animatio" +
                        "n-ultra-hd-4k-3840x2160-srjoecgyz-thumbnail-full01-on-blue-abstract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap videoblocks_blue_abstract_corporate_grunge_waves_motion_background_video_animation_ultra_hd_4k_3840x2160_srjoecgyz_thumbnail_full01_on_blue_abstract1 {
            get {
                object obj = ResourceManager.GetObject("videoblocks-blue-abstract-corporate-grunge-waves-motion-background-video-animatio" +
                        "n-ultra-hd-4k-3840x2160-srjoecgyz-thumbnail-full01-on-blue-abstract1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap will {
            get {
                object obj = ResourceManager.GetObject("will", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap withoutBACK {
            get {
                object obj = ResourceManager.GetObject("withoutBACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zeasbIs_XhM {
            get {
                object obj = ResourceManager.GetObject("zeasbIs_XhM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Снимок {
            get {
                object obj = ResourceManager.GetObject("Снимок", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
